name: samon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - geopandas>=0.13.2
  - shapely=2.0.1
  - tqdm=4.66.1
  - rasterio=1.3.6
  - scikit-learn=1.3.0
  - lxml=4.9.2
  - scipy=1.10.1
  - gdal=3.6.2
  - pyproj=3.5.0